GET_STATE, \
GET_RESULT, \
GET_STATS, \
GET_PARAMS, \
READ_SHORT_FILE, \
WRITE_SHORT_FILE, \
GET_PINS, \
RUN_CMD = range(8)

SDI12_SENSOR_1_SPID, \
SDI12_SENSOR_2_SPID, \
SDI12_SENSOR_3_SPID = range(11, 11+3)
